# html lang
language: en

# main menu navigation
menu:
  'About': /about
  'Archives': /archives

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/blog.css

# scripts loaded in the end of the body
scripts:
- /js/blog.js
- /js/prism.js
